requirements:
  interpreter: python >= 3.8
  python_packages:
    - matplotlib >= 3.7.2
    - Pillow >= 10.0.0
    - numpy >= 1.24.4
    - natsort >= 8.4.0
    - librosa >= 0.10.1
    - soundfile >= 0.12.1